
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE2_115(

	//////////// KEY //////////
	input [3:0] KEY,

	//////////// SW //////////
	input [17:0] SW,

	//////////// SEG7 //////////
	output [6:0] HEX0
	
);

wire [4:0] f;


Nacifra nacif(
					.s5(f[4]),
					.s4(f[3]),
					.s3(f[2]),
					.s2(f[1]),
					.s1(f[0]),
					
					.e4(SW[3]),
					.e3(SW[2]),
					.e2(SW[1]),
					.e1(SW[0]),
					
					.ready(~KEY[2]),
					.reset(~KEY[3])
);

Nasete naset(
	.d7(HEX0[6]),
	.d6(HEX0[5]),
	.d5(HEX0[4]),
	.d4(HEX0[3]),
	.d3(HEX0[2]),
	.d2(HEX0[1]),
	.d1(HEX0[0]),
	
	.s5(f[4]),
	.s4(f[3]),
	.s3(f[2]),
	.s2(f[1]),
	.s1(f[0])
);


endmodule
